---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: master, worker
  roles:
    - role: docker
      vars:
        version: "20.10.13"
  tags:
    - docker

- hosts: master, worker
  roles:
    - role: swarm
  tags:
    - swarm
